### PR TITLE
Add first bite :cake:

### PR DESCRIPTION
**Pull request by chezou**
Hi, I'd like to add first_bite.jpg.
The photo is not so clear, but I think it is very special one :smile_cat:

### CODE REVIEW

**Comment by katsuma** [comment]
Thanks. Can you rebase this branch on master?

**Comment by katsuma** [comment]
Sorry, can you add this image path to `api/sozais.json` ?

**Comment by chezou** [comment]
Added dcfea07

**Comment by chezou** [comment]
rebased and add api

**Comment by chezou** [comment]
@katsuma Can you merge it?

**Comment by katsuma** [comment]
Hmm. json file looks conflicted.

**Comment by chezou** [comment]
I've rebased it. Please recheck it!

**Comment by chezou** [comment]
sorry for conflicting. I've rebased....

**Comment by katsuma** [comment]
:+1:

**Pull request merged**
