### PR TITLE
Add somen.jpg

### PR DESCRIPTION
**Pull request by makimoto**
Hi!
In this pull request, I add somen.jpg.
If you like it, please merge.

### CODE REVIEW

**Comment by katsuma** [comment]
Thank you for your PR.

But I think this caption "somen" is not suitable for this image.
Do you have other ideas?

**Comment by gfx** [comment]
How about ”Architecting a stream of somen"?

**Comment by slightair** [comment]
I suggest "nagashi somen architect".

**Comment by katsuma** [comment]
@gfx @slightair 
`architect` sounds good.

**Comment by makimoto** [comment]
I rename somen to architect.
How bout it?

**Comment by katsuma** [comment]
:+1:

**Comment by katsuma** [comment]
@makimoto 
I found image path in index.html is wrong.
Can you check it again?

**Comment by katsuma** [comment]
And please add image path to `api/sozais.json`.

**Pull request merged**
